import {
  renderToBuffer, Document, Page, Text, View, Image,
  Svg, Polygon, StyleSheet,
} from "@react-pdf/renderer"
import { createElement } from "react"

// ── Types ─────────────────────────────────────────────────────────────────────

export type SpeakerForPdf = {
  firstName:    string
  lastName:     string
  role:         string | null
  company:      string | null
  photoUrl:     string | null
  priority:     number | null
  sessionTopic: string | null
}

export type PdfLayout = "cards" | "list" | "grid"

// ── Priority config ───────────────────────────────────────────────────────────

export const PRIO_PDF: Record<number, {
  filled: number; color: string; label: string; bg: string; text: string
}> = {
  1: { filled: 4, color: "#F59E0B", label: "Must meet", bg: "#FEF3C7", text: "#92400E" },
  2: { filled: 3, color: "#3B82F6", label: "Important",  bg: "#DBEAFE", text: "#1E40AF" },
  3: { filled: 2, color: "#9CA3AF", label: "Optional",   bg: "#F3F4F6", text: "#4B5563" },
  4: { filled: 1, color: "#EF4444", label: "Skip",       bg: "#FEE2E2", text: "#991B1B" },
}

export function prioOrder(p: number | null): number {
  if (p === 4) return 99
  if (p === null) return 10
  return p
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function initials(first: string, last: string) {
  return `${(first[0] ?? "").toUpperCase()}${(last[0] ?? "").toUpperCase()}`
}

// ── Diamond SVG row ───────────────────────────────────────────────────────────

function makeDiamonds(priority: number, sz = 6) {
  const cfg = PRIO_PDF[priority]
  return [1, 2, 3, 4].map((i) =>
    createElement(Svg, { key: i, width: sz, height: sz, viewBox: "0 0 8 8" },
      createElement(Polygon, {
        points: "4,0 8,4 4,8 0,4",
        fill:   i <= cfg.filled ? cfg.color : "none",
        stroke: i <= cfg.filled ? cfg.color : "#D1D5DB",
        strokeWidth: "1.5",
      })
    )
  )
}

// ── Shared page header / footer ───────────────────────────────────────────────

const sharedStyles = StyleSheet.create({
  header:   { backgroundColor: "#FFFFFF", borderRadius: 8, padding: 16, marginBottom: 16 },
  title:    { fontSize: 16, fontWeight: "bold", color: "#111827" },
  subtitle: { fontSize: 9, color: "#6B7280", marginTop: 4 },
  meta:     { fontSize: 8, color: "#9CA3AF", marginTop: 3 },
  footer:   {
    position: "absolute", bottom: 24, left: 32, right: 32,
    fontSize: 8, color: "#9CA3AF", textAlign: "center",
  },
})

function makeHeader(eventName: string, subtitle: string, count: number, ownerName: string) {
  return createElement(
    View, { style: sharedStyles.header },
    createElement(Text, { style: sharedStyles.title    }, eventName),
    createElement(Text, { style: sharedStyles.subtitle }, subtitle),
    createElement(Text, { style: sharedStyles.meta },
      `${count} speaker${count !== 1 ? "s" : ""} · Sorted by priority · ${ownerName} · ${new Date().toLocaleDateString("fr-FR")}`)
  )
}

function makeFooter() {
  return createElement(Text, { style: sharedStyles.footer }, "Generated by 6Degrees · 6degrees.app")
}

// ── LAYOUT: cards (multi-line with circular photo) ────────────────────────────

const cardStyles = StyleSheet.create({
  page:    { padding: 32, fontFamily: "Helvetica", backgroundColor: "#F9FAFB" },
  card: {
    backgroundColor: "#FFFFFF", borderRadius: 8, padding: 12, marginBottom: 6,
    flexDirection: "row", alignItems: "flex-start",
  },
  cardSkip:     { opacity: 0.5 },
  cardMustMeet: { borderTopWidth: 2, borderTopColor: "#F59E0B" },
  photoWrap: {
    width: 48, height: 48, borderRadius: 24,
    overflow: "hidden", marginRight: 12, flexShrink: 0,
  },
  photo: { width: 48, height: 48 },
  photoPlaceholder: {
    width: 48, height: 48, borderRadius: 24, backgroundColor: "#4F46E5",
    alignItems: "center", justifyContent: "center",
    marginRight: 12, flexShrink: 0,
  },
  photoInitials: { color: "#FFFFFF", fontSize: 15, fontWeight: "bold" },
  info:    { flex: 1 },
  prioBadge: {
    flexDirection: "row", alignItems: "center", borderRadius: 4,
    paddingTop: 2, paddingBottom: 2, paddingLeft: 5, paddingRight: 5,
    alignSelf: "flex-start", marginBottom: 4,
  },
  prioLabel: { fontSize: 7, fontWeight: "bold", marginLeft: 4 },
  name:    { fontSize: 11, fontWeight: "bold", color: "#111827", marginBottom: 2 },
  role:    { fontSize: 9,  color: "#6B7280", marginBottom: 1 },
  company: { fontSize: 9,  color: "#2563EB" },
})

function renderCardsLayout(
  speakers: SpeakerForPdf[],
  photoDataUrls: (string | null)[],
  eventName: string,
  subtitle: string,
  ownerName: string,
) {
  return createElement(
    Document, null,
    createElement(
      Page, { size: "A4", style: cardStyles.page },
      makeHeader(eventName, subtitle, speakers.length, ownerName),
      ...speakers.map((s, idx) => {
        const cfg   = s.priority !== null ? PRIO_PDF[s.priority] : null
        const photo = photoDataUrls[idx]
        const inits = initials(s.firstName, s.lastName)
        const cardStyle = Object.assign(
          {},
          cardStyles.card,
          s.priority === 1 ? cardStyles.cardMustMeet : {},
          s.priority === 4 ? cardStyles.cardSkip     : {},
        )
        return createElement(
          View, { key: idx, style: cardStyle },
          photo
            ? createElement(View, { style: cardStyles.photoWrap },
                createElement(Image, { src: photo, style: cardStyles.photo })
              )
            : createElement(View, { style: cardStyles.photoPlaceholder },
                createElement(Text, { style: cardStyles.photoInitials }, inits)
              ),
          createElement(
            View, { style: cardStyles.info },
            cfg
              ? createElement(
                  View, { style: Object.assign({}, cardStyles.prioBadge, { backgroundColor: cfg.bg }) },
                  ...makeDiamonds(s.priority!),
                  createElement(Text, { style: Object.assign({}, cardStyles.prioLabel, { color: cfg.text }) }, cfg.label)
                )
              : null,
            createElement(Text, { style: cardStyles.name    }, `${s.firstName} ${s.lastName}`),
            s.role    ? createElement(Text, { style: cardStyles.role    }, s.role)    : null,
            s.company ? createElement(Text, { style: cardStyles.company }, s.company) : null,
          )
        )
      }),
      makeFooter()
    )
  )
}

// ── LAYOUT: list (compact table — all info on one line per speaker) ───────────

const PHOTO_SZ = 26

const listStyles = StyleSheet.create({
  page: { padding: 28, fontFamily: "Helvetica", backgroundColor: "#F9FAFB" },
  row: {
    flexDirection: "row", alignItems: "center",
    paddingVertical: 5, paddingHorizontal: 8,
    borderBottomWidth: 0.5, borderBottomColor: "#E5E7EB",
  },
  rowOdd:  { backgroundColor: "#FFFFFF" },
  rowEven: { backgroundColor: "#F9FAFB" },
  rowSkip: { opacity: 0.5 },
  photoWrap: {
    width: PHOTO_SZ, height: PHOTO_SZ, borderRadius: PHOTO_SZ / 2,
    overflow: "hidden", marginRight: 10, flexShrink: 0,
  },
  photo: { width: PHOTO_SZ, height: PHOTO_SZ },
  photoPlaceholder: {
    width: PHOTO_SZ, height: PHOTO_SZ, borderRadius: PHOTO_SZ / 2,
    backgroundColor: "#4F46E5", alignItems: "center", justifyContent: "center",
    marginRight: 10, flexShrink: 0,
  },
  photoInitials: { color: "#FFFFFF", fontSize: 8, fontWeight: "bold" },
  prioWrap: {
    flexDirection: "row", alignItems: "center",
    width: 44, marginRight: 10, flexShrink: 0,
  },
  nameCol:    { flex: 5, marginRight: 8 },
  name:       { fontSize: 11, fontWeight: "bold", color: "#111827" },
  roleCol:    { flex: 5, marginRight: 8 },
  role:       { fontSize: 10, color: "#6B7280" },
  companyCol: { flex: 4 },
  company:    { fontSize: 10, color: "#2563EB" },
  headerRow: {
    flexDirection: "row", alignItems: "center",
    paddingVertical: 4, paddingHorizontal: 8,
    backgroundColor: "#F3F4F6", borderBottomWidth: 1, borderBottomColor: "#D1D5DB",
    marginBottom: 0,
  },
  headerText: { fontSize: 7, fontWeight: "bold", color: "#6B7280", textTransform: "uppercase" },
})

function renderListLayout(
  speakers: SpeakerForPdf[],
  photoDataUrls: (string | null)[],
  eventName: string,
  subtitle: string,
  ownerName: string,
) {
  return createElement(
    Document, null,
    createElement(
      Page, { size: "A4", style: listStyles.page },
      makeHeader(eventName, subtitle, speakers.length, ownerName),
      // Column headers
      createElement(
        View, { style: listStyles.headerRow },
        createElement(View, { style: { width: PHOTO_SZ, marginRight: 10 } }),
        createElement(View, { style: { width: 44, marginRight: 10 } },
          createElement(Text, { style: listStyles.headerText }, "Priority")
        ),
        createElement(View, { style: listStyles.nameCol },
          createElement(Text, { style: listStyles.headerText }, "Name")
        ),
        createElement(View, { style: listStyles.roleCol },
          createElement(Text, { style: listStyles.headerText }, "Title")
        ),
        createElement(View, { style: listStyles.companyCol },
          createElement(Text, { style: listStyles.headerText }, "Company")
        ),
      ),
      ...speakers.map((s, idx) => {
        const cfg   = s.priority !== null ? PRIO_PDF[s.priority] : null
        const photo = photoDataUrls[idx]
        const inits = initials(s.firstName, s.lastName)
        const rowStyle = Object.assign(
          {},
          listStyles.row,
          idx % 2 === 0 ? listStyles.rowOdd : listStyles.rowEven,
          s.priority === 4 ? listStyles.rowSkip : {},
        )
        return createElement(
          View, { key: idx, style: rowStyle },
          // Photo
          photo
            ? createElement(View, { style: listStyles.photoWrap },
                createElement(Image, { src: photo, style: listStyles.photo })
              )
            : createElement(View, { style: listStyles.photoPlaceholder },
                createElement(Text, { style: listStyles.photoInitials }, inits)
              ),
          // Priority diamonds
          createElement(
            View, { style: listStyles.prioWrap },
            cfg ? createElement(View, { style: { flexDirection: "row" } }, ...makeDiamonds(s.priority!, 5)) : null,
          ),
          // Name
          createElement(View, { style: listStyles.nameCol },
            createElement(Text, { style: listStyles.name }, `${s.firstName} ${s.lastName}`),
          ),
          // Role / title
          createElement(View, { style: listStyles.roleCol },
            s.role ? createElement(Text, { style: listStyles.role }, s.role) : null,
          ),
          // Company
          createElement(View, { style: listStyles.companyCol },
            s.company ? createElement(Text, { style: listStyles.company }, s.company) : null,
          ),
        )
      }),
      makeFooter()
    )
  )
}

// ── LAYOUT: grid (3-column with square photos) ────────────────────────────────

const gridStyles = StyleSheet.create({
  page:     { padding: 32, fontFamily: "Helvetica", backgroundColor: "#F9FAFB" },
  grid:     { flexDirection: "row", flexWrap: "wrap" },
  cell:     { width: "33%", padding: 4 },
  card:     { backgroundColor: "#FFFFFF", borderRadius: 6, overflow: "hidden" },
  cardMM:   { borderTopWidth: 2, borderTopColor: "#F59E0B" },
  cardSkip: { opacity: 0.5 },
  photoWrap:{ width: "100%", aspectRatio: 1, position: "relative", backgroundColor: "#E5E7EB" },
  photo:    { width: "100%", height: "100%" },
  initials: {
    width: "100%", height: "100%", backgroundColor: "#4F46E5",
    alignItems: "center", justifyContent: "center",
  },
  initialsText: { color: "#FFFFFF", fontSize: 20, fontWeight: "bold" },
  badge: {
    position: "absolute", top: 4, left: 4,
    flexDirection: "row", borderRadius: 3,
    paddingTop: 1, paddingBottom: 1, paddingLeft: 3, paddingRight: 3,
  },
  body:    { padding: 6 },
  name:    { fontSize: 8, fontWeight: "bold", color: "#111827" },
  company: { fontSize: 7, color: "#6B7280", marginTop: 1 },
})

function renderGridLayout(
  speakers: SpeakerForPdf[],
  photoDataUrls: (string | null)[],
  eventName: string,
  subtitle: string,
  ownerName: string,
) {
  return createElement(
    Document, null,
    createElement(
      Page, { size: "A4", style: gridStyles.page },
      makeHeader(eventName, subtitle, speakers.length, ownerName),
      createElement(
        View, { style: gridStyles.grid },
        ...speakers.map((s, idx) => {
          const cfg   = s.priority !== null ? PRIO_PDF[s.priority] : null
          const photo = photoDataUrls[idx]
          const inits = initials(s.firstName, s.lastName)
          const cardStyle = Object.assign(
            {},
            gridStyles.card,
            s.priority === 1 ? gridStyles.cardMM   : {},
            s.priority === 4 ? gridStyles.cardSkip : {},
          )
          return createElement(
            View, { key: idx, style: gridStyles.cell },
            createElement(
              View, { style: cardStyle },
              createElement(
                View, { style: gridStyles.photoWrap },
                photo
                  ? createElement(Image, { src: photo, style: gridStyles.photo })
                  : createElement(View, { style: gridStyles.initials },
                      createElement(Text, { style: gridStyles.initialsText }, inits)
                    ),
                cfg
                  ? createElement(
                      View, { style: Object.assign({}, gridStyles.badge, { backgroundColor: cfg.bg }) },
                      ...makeDiamonds(s.priority!)
                    )
                  : null,
              ),
              createElement(
                View, { style: gridStyles.body },
                createElement(Text, { style: gridStyles.name }, `${s.firstName} ${s.lastName}`),
                s.company ? createElement(Text, { style: gridStyles.company }, s.company) : null,
              ),
            )
          )
        })
      ),
      makeFooter()
    )
  )
}

// ── Main export ───────────────────────────────────────────────────────────────

const IMAGE_HEADERS = {
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  "Accept": "image/png,image/jpeg,image/*;q=0.5",
  "Accept-Language": "en-US,en;q=0.9",
  "Referer": "https://europe.money2020.com/",
}

async function prefetchPhoto(url: string): Promise<string | null> {
  // Force PNG since CDN returns WebP by default and PDFKit has no WebP decoder.
  const pngUrl = url.replace(/([?&]format=)\w+/i, "$1png")
  try {
    const res = await fetch(pngUrl, {
      signal: AbortSignal.timeout(8000),
      redirect: "follow",
      headers: IMAGE_HEADERS,
    })
    if (!res.ok) {
      console.warn(`[PDF photo] ${res.status} for ${pngUrl.slice(0, 80)}`)
      return null
    }
    const buf = await res.arrayBuffer()
    if (buf.byteLength < 100) return null
    const ct = res.headers.get("content-type") ?? ""
    if (!ct.startsWith("image/") || ct.includes("webp")) {
      console.warn(`[PDF photo] unexpected content-type=${ct}`)
      return null
    }
    return `data:${ct};base64,${Buffer.from(buf).toString("base64")}`
  } catch (e) {
    console.warn(`[PDF photo] fetch error: ${e}`)
    return null
  }
}

export async function generateSpeakersPdf({
  eventName,
  subtitle,
  speakers,
  ownerName,
  layout = "cards",
}: {
  eventName: string
  subtitle:  string
  speakers:  SpeakerForPdf[]
  ownerName: string
  layout?:   PdfLayout
}): Promise<Buffer> {
  // Pre-fetch all images server-side with browser-like headers so PDFKit
  // receives properly-typed image bytes and never tries its own CDN fetch.
  const photoSrcs = await Promise.all(
    speakers.map((s) => (s.photoUrl ? prefetchPhoto(s.photoUrl) : Promise.resolve(null)))
  )

  const fetched = photoSrcs.filter(Boolean).length
  console.log(`[PDF] layout=${layout} speakers=${speakers.length} photos=${fetched}`)

  let doc: ReturnType<typeof createElement>
  if (layout === "list") {
    doc = renderListLayout(speakers, photoSrcs, eventName, subtitle, ownerName)
  } else if (layout === "grid") {
    doc = renderGridLayout(speakers, photoSrcs, eventName, subtitle, ownerName)
  } else {
    doc = renderCardsLayout(speakers, photoSrcs, eventName, subtitle, ownerName)
  }

  const buffer = await (renderToBuffer(doc as Parameters<typeof renderToBuffer>[0]) as Promise<Buffer>)
  console.log(`[PDF] renderToBuffer done bytes=${buffer.length}`)
  return buffer
}
