import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import prisma from "@/lib/prisma"
import { renderToBuffer, Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer"
import { createElement } from "react"

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica" },
  header: { marginBottom: 24 },
  title: { fontSize: 22, fontWeight: "bold", color: "#111827" },
  description: { fontSize: 11, color: "#6B7280", marginTop: 4 },
  meta: { fontSize: 10, color: "#9CA3AF", marginTop: 4 },
  table: { marginTop: 16 },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    paddingVertical: 8,
    alignItems: "center",
  },
  rowHeader: {
    flexDirection: "row",
    borderBottomWidth: 2,
    borderBottomColor: "#E5E7EB",
    paddingVertical: 8,
    marginBottom: 2,
  },
  colName: { width: "25%", fontSize: 10, color: "#111827", fontWeight: "bold" },
  colTitle: { width: "25%", fontSize: 10, color: "#374151" },
  colCompany: { width: "25%", fontSize: 10, color: "#374151" },
  colLocation: { width: "25%", fontSize: 10, color: "#6B7280" },
  colNameH: { width: "25%", fontSize: 9, color: "#6B7280", fontWeight: "bold" },
  colTitleH: { width: "25%", fontSize: 9, color: "#6B7280", fontWeight: "bold" },
  colCompanyH: { width: "25%", fontSize: 9, color: "#6B7280", fontWeight: "bold" },
  colLocationH: { width: "25%", fontSize: 9, color: "#6B7280", fontWeight: "bold" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 9, color: "#9CA3AF", textAlign: "center" },
})

type Contact = {
  firstName: string
  lastName: string
  position: string | null
  company: string | null
  location: string | null
}

function ListPdf({
  listName,
  description,
  contacts,
  ownerName,
}: {
  listName: string
  description: string | null
  contacts: Contact[]
  ownerName: string
}) {
  return createElement(
    Document,
    null,
    createElement(
      Page,
      { size: "A4", style: styles.page },
      // Header
      createElement(
        View,
        { style: styles.header },
        createElement(Text, { style: styles.title }, listName),
        description ? createElement(Text, { style: styles.description }, description) : null,
        createElement(
          Text,
          { style: styles.meta },
          `${contacts.length} contact${contacts.length !== 1 ? "s" : ""} · ${ownerName} · ${new Date().toLocaleDateString("fr-FR")}`
        )
      ),
      // Table header
      createElement(
        View,
        { style: styles.rowHeader },
        createElement(Text, { style: styles.colNameH }, "NAME"),
        createElement(Text, { style: styles.colTitleH }, "TITLE"),
        createElement(Text, { style: styles.colCompanyH }, "COMPANY"),
        createElement(Text, { style: styles.colLocationH }, "LOCATION")
      ),
      // Rows
      createElement(
        View,
        { style: styles.table },
        ...contacts.map((c, i) =>
          createElement(
            View,
            { key: i, style: styles.row },
            createElement(Text, { style: styles.colName }, `${c.firstName} ${c.lastName}`),
            createElement(Text, { style: styles.colTitle }, c.position ?? "—"),
            createElement(Text, { style: styles.colCompany }, c.company ?? "—"),
            createElement(Text, { style: styles.colLocation }, c.location ?? "—")
          )
        )
      ),
      // Footer
      createElement(Text, { style: styles.footer }, "Generated by 6Degrees · 6degrees.app")
    )
  )
}

export async function GET(
  _req: Request,
  { params }: { params: { id: string } }
) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) return new Response("Unauthorized", { status: 401 })

  const list = await prisma.contactList.findFirst({
    where: { id: params.id, userId: session.user.id },
    include: {
      members: { include: { contact: true } },
      user: { select: { name: true } },
    },
  })
  if (!list) return new Response("Not found", { status: 404 })

  const contacts = list.members.map((m) => m.contact)

  const buffer = await renderToBuffer(
    createElement(ListPdf, {
      listName: list.name,
      description: list.description,
      contacts,
      ownerName: list.user.name ?? "Unknown",
    }) as Parameters<typeof renderToBuffer>[0]
  )

  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${list.name.replace(/[^a-z0-9]/gi, "_")}.pdf"`,
    },
  })
}
