import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import prisma from "@/lib/prisma"

// Enable or disable sharing; returns the share URL
export async function POST(
  _req: Request,
  { params }: { params: { id: string } }
) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) return new Response("Unauthorized", { status: 401 })

  const list = await prisma.contactList.findFirst({
    where: { id: params.id, userId: session.user.id },
  })
  if (!list) return new Response("Not found", { status: 404 })

  // Ensure a shareToken exists (it's generated by default via @default(cuid()))
  const updated = await prisma.contactList.update({
    where: { id: params.id },
    data: { shareEnabled: true },
  })

  const baseUrl = process.env.NEXTAUTH_URL ?? "http://localhost:3000"
  return Response.json({
    shareToken: updated.shareToken,
    shareUrl: `${baseUrl}/share/${updated.shareToken}`,
  })
}

export async function DELETE(
  _req: Request,
  { params }: { params: { id: string } }
) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) return new Response("Unauthorized", { status: 401 })

  await prisma.contactList.updateMany({
    where: { id: params.id, userId: session.user.id },
    data: { shareEnabled: false },
  })
  return Response.json({ ok: true })
}
