import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import prisma from "@/lib/prisma"
import { renderToBuffer, Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"
import { createElement } from "react"

// ── Styles ────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  page:    { padding: 36, fontFamily: "Helvetica" },
  header:  { marginBottom: 16 },
  title:   { fontSize: 16, fontWeight: "bold", color: "#111827" },
  subtitle:{ fontSize: 9,  color: "#6B7280", marginTop: 3 },
  meta:    { fontSize: 8,  color: "#9CA3AF", marginTop: 3 },
  rowHeader: {
    flexDirection: "row",
    borderBottomWidth: 2,
    borderBottomColor: "#E5E7EB",
    paddingVertical: 5,
    marginBottom: 2,
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    paddingVertical: 5,
    alignItems: "flex-start",
  },
  // Column widths — A4 portrait 4-column layout
  cName:    { width: "30%", fontSize: 8, color: "#111827", fontWeight: "bold" },
  cRole:    { width: "25%", fontSize: 8, color: "#374151" },
  cCompany: { width: "25%", fontSize: 8, color: "#374151" },
  cLi:      { width: "20%", fontSize: 8, color: "#2563EB" },
  hName:    { width: "30%", fontSize: 7, color: "#9CA3AF", fontWeight: "bold" },
  hRole:    { width: "25%", fontSize: 7, color: "#9CA3AF", fontWeight: "bold" },
  hCompany: { width: "25%", fontSize: 7, color: "#9CA3AF", fontWeight: "bold" },
  hLi:      { width: "20%", fontSize: 7, color: "#9CA3AF", fontWeight: "bold" },
  footer: {
    position: "absolute", bottom: 28, left: 36, right: 36,
    fontSize: 8, color: "#9CA3AF", textAlign: "center",
  },
})

// ── Types ─────────────────────────────────────────────────────────────────────

type SpeakerRow = {
  firstName: string
  lastName:  string
  role:      string | null
  company:   string | null
  contact: {
    connectedOn:    string | null
    linkedinDegree: string | null
  } | null
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function liStatus(s: SpeakerRow): string {
  const c = s.contact
  if (!c) return ""
  if (c.connectedOn || c.linkedinDegree === "1") return "Connected"
  return ""
}

// ── PDF component ─────────────────────────────────────────────────────────────

function SpeakersPdf({
  eventName, subtitle, speakers, ownerName,
}: {
  eventName: string
  subtitle:  string
  speakers:  SpeakerRow[]
  ownerName: string
}) {
  return createElement(
    Document,
    null,
    createElement(
      Page,
      { size: "A4", style: styles.page },
      // Header
      createElement(
        View, { style: styles.header },
        createElement(Text, { style: styles.title }, eventName),
        createElement(Text, { style: styles.subtitle }, subtitle),
        createElement(Text, { style: styles.meta },
          `${speakers.length} speaker${speakers.length !== 1 ? "s" : ""} · ${ownerName} · ${new Date().toLocaleDateString("fr-FR")}`)
      ),
      // Table header
      createElement(
        View, { style: styles.rowHeader },
        createElement(Text, { style: styles.hName    }, "NAME"),
        createElement(Text, { style: styles.hRole    }, "ROLE"),
        createElement(Text, { style: styles.hCompany }, "COMPANY"),
        createElement(Text, { style: styles.hLi      }, "LINKEDIN"),
      ),
      // Rows
      createElement(
        View, {},
        ...speakers.map((s, i) =>
          createElement(
            View, { key: i, style: styles.row },
            createElement(Text, { style: styles.cName    }, `${s.firstName} ${s.lastName}`),
            createElement(Text, { style: styles.cRole    }, s.role    ?? "—"),
            createElement(Text, { style: styles.cCompany }, s.company ?? "—"),
            createElement(Text, { style: styles.cLi      }, liStatus(s)),
          )
        )
      ),
      // Footer
      createElement(Text, { style: styles.footer }, "Generated by 6Degrees · 6degrees.app")
    )
  )
}

// ── Route ─────────────────────────────────────────────────────────────────────

export async function POST(req: Request) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) return new Response("Unauthorized", { status: 401 })
  const userId = session.user.id

  const body = await req.json().catch(() => ({}))
  const eventSlug: string  = body.eventSlug ?? "money2020-europe-2026"
  const eventName: string  = body.eventName ?? "Money 20/20 Europe 2026"
  const subtitle:  string  = body.subtitle  ?? "All speakers"
  const ids: string[] | undefined = Array.isArray(body.speakerIds) && body.speakerIds.length > 0
    ? body.speakerIds
    : undefined

  const speakers = await prisma.eventSpeaker.findMany({
    where: {
      userId,
      eventSlug,
      ...(ids ? { id: { in: ids } } : {}),
    },
    select: {
      firstName: true,
      lastName:  true,
      role:      true,
      company:   true,
      contact: {
        select: { connectedOn: true, linkedinDegree: true },
      },
    },
    orderBy: [{ lastName: "asc" }, { firstName: "asc" }],
  })

  const filename = `${eventName.replace(/[^a-z0-9]/gi, "_")}_speakers.pdf`

  const buffer = await renderToBuffer(
    createElement(SpeakersPdf, {
      eventName,
      subtitle,
      speakers: speakers as SpeakerRow[],
      ownerName: session.user.name ?? "Unknown",
    }) as Parameters<typeof renderToBuffer>[0]
  )

  return new Response(new Uint8Array(buffer), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  })
}
